package codegen_java

import (
	"maps"
	"slices"
	"strings"

	"github.com/tempo-lang/tempo/projection"
)

func (gen *codegen) GenSourceFile(s *projection.SourceFile) string {
	var out strings.Builder
	out.WriteString(gen.Writeln("// Code generated by tempo, DO NOT EDIT."))

	if gen.opts.Package != nil {
		out.WriteString(gen.Writeln("package %s;", *gen.opts.Package))
		out.WriteString(gen.Writeln(""))
	}

	code := gen.GenMainClass(s)

	for _, pkg := range slices.Sorted(maps.Keys(gen.imports)) {
		out.WriteString(gen.Writeln("import %s;", pkg))
	}
	out.WriteString(gen.Writeln(""))

	out.WriteString(code)

	return out.String()
}

func (gen *codegen) GenMainClass(s *projection.SourceFile) string {
	var out strings.Builder
	out.WriteString(gen.Writeln("public final class %s {", gen.opts.ClassName))
	gen.IncIndent()

	out.WriteString(gen.Writeln("private %s() {}", gen.opts.ClassName))

	for _, inf := range s.Interfaces {
		out.WriteString(gen.GenChoreographyInterface(inf))
	}

	for _, st := range s.Structs {
		out.WriteString(gen.GenChoreographyStruct(st))
	}

	for _, chor := range s.Chors {
		out.WriteString(gen.GenChoreography(chor))
	}

	gen.DecIndent()
	out.WriteString(gen.Writeln("}"))

	return out.String()
}
