package codegen_java

import (
	"github.com/tempo-lang/tempo/projection"
)

func (gen *codegen) GenSourceFile(s *projection.SourceFile) string {
	out := gen.Writeln("// Code generated by tempo, DO NOT EDIT.\n")

	if gen.opts.Package != nil {
		out += gen.Writeln("package %s;\n", gen.opts.Package)
	}

	out += gen.Writeln("public final class %s {", gen.opts.ClassName)
	gen.IncIndent()

	out += gen.Writeln("private %s() {}", gen.opts.ClassName)

	// for _, inf := range s.Interfaces {
	// 	out += gen.GenChoreographyInterface(inf)
	// }

	// for _, st := range s.Structs {
	// 	out += gen.GenChoreographyStruct(st)
	// }

	for _, chor := range s.Chors {
		out += gen.GenChoreography(chor)
	}

	gen.DecIndent()
	out += gen.Writeln("}")

	return out
}
