// Code generated by tempo, DO NOT EDIT.
package loop;

import tempo.runtime.Env;

public final class Choreography {
  private Choreography() {}
  
  // Projection of choreography `Main`
  public static void Main_A(Env env) throws Exception {
    Integer i = 5;
    while (env.send(i > 0, "B").get()) {
      env.<String>recv("B").get();
      i = i - 1;
    }
  }
  public static void Main_B(Env env) throws Exception {
    while (env.<Boolean>recv("A").get()) {
      env.send("ping", "A").get();
    }
  }
}
