// Code generated by tempo, DO NOT EDIT.
package loop

import runtime "github.com/tempo-lang/tempo/runtime"

// Projection of choreography `Main`
func Main_A(env *runtime.Env) {
	var i int = 5
	_ = i
	runtime.Send(env, i > 0, "B")
	for i > 0 {
		_ = runtime.GetAsync(runtime.Recv[string](env, "B"))
		i = i - 1
	}
}
func Main_B(env *runtime.Env) {
	for runtime.GetAsync(runtime.Recv[bool](env, "A")) {
		runtime.Send(env, "ping", "A")
	}
}
