// Code generated by tempo, DO NOT EDIT.
package send_trans

import runtime "tempo/runtime"

// Projection of choreography Trans
func Trans_A(env *runtime.Env) {
	var x int = 10
	_ = x
	runtime.Send(env, x, "B")
	var y int = x
	_ = y
	var z int = y
	_ = z
}
func Trans_B(env *runtime.Env) {
	var y int = runtime.GetAsync(runtime.Recv[int](env, "A"))
	_ = y
	runtime.Send(env, y, "C")
	var z int = y
	_ = z
}
func Trans_C(env *runtime.Env) {
	var z int = runtime.GetAsync(runtime.Recv[int](env, "B"))
	_ = z
}
