// Code generated by chorego, DO NOT EDIT.
package simple_send

import runtime "chorego/runtime"

// Projection of choreography SimpleSend
func SimpleSend_A(env *runtime.Env) {
	var x int = 10
	_ = x // Suppress unused variable error
	env.Send(x, "B")
}
func SimpleSend_B(env *runtime.Env) {
	var y int = env.Recv("A").Get().(int)
	_ = y // Suppress unused variable error
}
