// Code generated by tempo, DO NOT EDIT.
package remote_procedure_call;

import java.util.concurrent.Future;
import tempo.runtime.Env;
import tempo.runtime.function.FnRet1;

public final class Choreography {
  private Choreography() {}
  // Projection of interface `RPC`
  public interface RPC_A {
    public Future<Integer> Call(Env env, Integer input) throws Exception;
  }
  public interface RPC_B {
    public void Call(Env env) throws Exception;
  }
  
  // Projection of struct `RemoteCall`
  public static final class RemoteCall_A implements Cloneable, RPC_A {
    public RemoteCall_A() {
    }
    
    public Future<Integer> Call(Env env, Integer input) throws Exception {
      env.send(input, "B").get();
      return env.<Integer>recv("B");
    }
    
    public RemoteCall_A clone() {
      return new RemoteCall_A();
    }
  }
  public static final class RemoteCall_B implements Cloneable, RPC_B {
    public FnRet1<Integer, Integer> Fn;
    
    public RemoteCall_B(FnRet1<Integer, Integer> Fn) {
      this.Fn = Fn;
    }
    
    public void Call(Env env) throws Exception {
      Integer output = this.Fn.call(env.<Integer>recv("A").get());
      env.send(output, "A");
    }
    
    public RemoteCall_B clone() {
      return new RemoteCall_B(Fn);
    }
  }
  
  // Projection of choreography `Start`
  public static void Start_A(Env env) throws Exception {
    RPC_A rpc = new RemoteCall_A();
    Integer result = rpc.Call(env, 10).get();
  }
  public static void Start_B(Env env) throws Exception {
    FnRet1<Integer, Integer> timesTwo = (input) -> {
      return input * 2;
    };
    RPC_B rpc = new RemoteCall_B(timesTwo);
    rpc.Call(env);
  }
}
