package projection

import (
	"chorego/parser"

	"github.com/dave/jennifer/jen"
)

type Choreography struct {
	Name  string
	Funcs map[string]*Func
}

func NewChoreography(name string) *Choreography {
	return &Choreography{
		Name:  name,
		Funcs: map[string]*Func{},
	}
}

func (c *Choreography) AddFunc(role string, funcCtx parser.IFuncContext) *Func {
	c.Funcs[role] = &Func{
		Choreography: c,
		FuncCtx:      funcCtx,
		Name:         funcCtx.Ident().GetText(),
		Role:         role,
	}
	return c.Funcs[role]
}

func (c *Choreography) Codegen(file *jen.File) {
	file.PackageComment("Code generated by chorego, DO NOT EDIT.")

	file.Commentf("Projection of choreography %s", c.Name)
	for _, v := range c.Funcs {
		v.Codegen(file)
	}

}
