package projection

import "github.com/dave/jennifer/jen"

type SourceFile struct {
	Structs []*ChoreographyStruct
	Chors   []*Choreography
}

func NewSourceFile() *SourceFile {
	return &SourceFile{
		Chors: []*Choreography{},
	}
}

func (s *SourceFile) AddChoreography(chor *Choreography) {
	s.Chors = append(s.Chors, chor)
}

func (s *SourceFile) AddStruct(st *ChoreographyStruct) {
	s.Structs = append(s.Structs, st)
}

func (s *SourceFile) Codegen(file *jen.File) {
	file.PackageComment("Code generated by tempo, DO NOT EDIT.")

	for _, st := range s.Structs {
		st.Codegen(file)
	}

	for _, chor := range s.Chors {
		chor.Codegen(file)
	}
}
