package projection

import "github.com/dave/jennifer/jen"

type SourceFile struct {
	Chors []*Choreography
}

func NewSourceFile() *SourceFile {
	return &SourceFile{
		Chors: []*Choreography{},
	}
}

func (s *SourceFile) AddChoreography(chor *Choreography) {
	s.Chors = append(s.Chors, chor)
}

func (s *SourceFile) Codegen(file *jen.File) {
	file.PackageComment("Code generated by chorego, DO NOT EDIT.")

	for _, chor := range s.Chors {
		chor.Codegen(file)
	}
}
