// Code generated by tempo, DO NOT EDIT.
package shift_roles;

import tempo.runtime.Env;

public final class Choreography {
  private Choreography() {}
  
  // Projection of choreography `ShiftRoles`
  public static void ShiftRoles_A(Env env, Integer count) throws Exception {
    if (count > 0) {
      env.send(count, "B").get();
      ShiftRoles_D(env.subst("B", "A", "C", "B", "D", "C", "A", "D"), count - 1);
    }
  }
  public static void ShiftRoles_B(Env env, Integer count) throws Exception {
    if (count > 0) {
      env.<Integer>recv("A").get();
      ShiftRoles_A(env.subst("B", "A", "C", "B", "D", "C", "A", "D"), count - 1);
    }
  }
  public static void ShiftRoles_C(Env env, Integer count) throws Exception {
    if (count > 0) {
      ShiftRoles_B(env.subst("B", "A", "C", "B", "D", "C", "A", "D"), count - 1);
    }
  }
  public static void ShiftRoles_D(Env env, Integer count) throws Exception {
    if (count > 0) {
      ShiftRoles_C(env.subst("B", "A", "C", "B", "D", "C", "A", "D"), count - 1);
    }
  }
}
