// Code generated by tempo, DO NOT EDIT.

import { Env } from '../../typescript/runtime.ts';

// Projection of choreography `ShiftRoles`
export async function ShiftRoles_A(env: Env, count: number) {
  if (count > 0) {
    env.send(count, "B");
    await ShiftRoles_D(env.subst("B", "A", "C", "B", "D", "C", "A", "D"), count - 1);
  }
}
export async function ShiftRoles_B(env: Env, count: number) {
  if (count > 0) {
    await env.recv<number>("A");
    await ShiftRoles_A(env.subst("B", "A", "C", "B", "D", "C", "A", "D"), count - 1);
  }
}
export async function ShiftRoles_C(env: Env, count: number) {
  if (count > 0) {
    await ShiftRoles_B(env.subst("B", "A", "C", "B", "D", "C", "A", "D"), count - 1);
  }
}
export async function ShiftRoles_D(env: Env, count: number) {
  if (count > 0) {
    await ShiftRoles_C(env.subst("B", "A", "C", "B", "D", "C", "A", "D"), count - 1);
  }
}

