package codegen_ts

import (
	"strings"

	"github.com/tempo-lang/tempo/projection"
)

func (gen *codegen) GenSourceFile(s *projection.SourceFile) string {
	var out strings.Builder
	out.WriteString(gen.Writeln("// Code generated by tempo, DO NOT EDIT.\n"))

	if !gen.opts.DisableTypes {
		out.WriteString(gen.Writeln("import { Env } from '%s';\n", gen.opts.RuntimePath))
	}

	if !gen.opts.DisableTypes {
		for _, inf := range s.Interfaces {
			out.WriteString(gen.GenChoreographyInterface(inf))
		}
	}

	for _, st := range s.Structs {
		out.WriteString(gen.GenChoreographyStruct(st))
	}

	for _, chor := range s.Chors {
		out.WriteString(gen.GenChoreography(chor))
	}

	return out.String()
}
