package codegen_ts

import (
	"github.com/tempo-lang/tempo/projection"
)

func (gen *codegen) GenSourceFile(s *projection.SourceFile) string {
	out := gen.Writeln("// Code generated by tempo, DO NOT EDIT.\n")

	out += gen.Writeln("import { Env } from './runtime.ts';\n")

	if !gen.opts.DisableTypes {
		for _, inf := range s.Interfaces {
			out += gen.GenChoreographyInterface(inf)
		}

		for _, st := range s.Structs {
			out += gen.GenChoreographyStruct(st)
		}
	}

	for _, chor := range s.Chors {
		out += gen.GenChoreography(chor)
	}

	return out
}
