package codegen_ts

import (
	"github.com/tempo-lang/tempo/projection"
)

func (gen *codegen) GenSourceFile(s *projection.SourceFile) {
	gen.Writeln("Code generated by tempo, DO NOT EDIT.\n")

	for _, inf := range s.Interfaces {
		gen.GenChoreographyInterface(inf)
	}

	for _, st := range s.Structs {
		// GenChoreographyStruct(file, st)
		gen.Writeln("[Struct %s]", st.Name)
	}

	for _, chor := range s.Chors {
		// GenChoreography(file, chor)
		gen.Writeln("[Choreography %s]", chor.Name)
	}
}
