// Code generated by tempo, DO NOT EDIT.
package ping_pong

import runtime "tempo/runtime"

// Projection of choreography pingPong
func pingPong_A(env *runtime.Env, count int) {
	if count > 0 {
		runtime.Send(env, count, "B")
		pingPong_B(env.Subst("B", "A", "A", "B"), count-1)
	}
}
func pingPong_B(env *runtime.Env, count int) {
	if count > 0 {
		var result int = runtime.GetAsync(runtime.Recv[int](env, "A"))
		_ = result
		pingPong_A(env.Subst("B", "A", "A", "B"), count-1)
	}
}

// Projection of choreography Start
func Start_A(env *runtime.Env) {
	pingPong_A(env.Subst("A", "A", "B", "B"), 4)
}
func Start_B(env *runtime.Env) {
	pingPong_B(env.Subst("A", "A", "B", "B"), 4)
}
