// Code generated by tempo, DO NOT EDIT.
package send_simple

import runtime "tempo/runtime"

// Projection of choreography SimpleSend
func SimpleSend_A(env *runtime.Env) {
	var x int = 10
	_ = x
	env.Send(x, "B")
}
func SimpleSend_B(env *runtime.Env) {
	var y int = env.Recv("A").Get().(int)
	_ = y
}
