// Code generated by tempo, DO NOT EDIT.
package send_simple

import runtime "tempo/runtime"

// Projection of choreography SimpleSend
func SimpleSend_A(env *runtime.Env) {
	var x int = 10
	_ = x
	runtime.Send(env, x, "B")
}
func SimpleSend_B(env *runtime.Env) {
	var y int = runtime.GetAsync(runtime.Recv[int](env, "A"))
	_ = y
}
