// Code generated by tempo, DO NOT EDIT.
package send_trans;

import tempo.runtime.Env;

public final class Choreography {
  private Choreography() {}
  
  // Projection of choreography `Trans`
  public static void Trans_A(Env env) throws Exception {
    Integer x = 10;
    Integer y = env.send(x, "B").get();
    Integer z = y;
  }
  public static void Trans_B(Env env) throws Exception {
    Integer y = env.<Integer>recv("A").get();
    Integer z = env.send(y, "C").get();
  }
  public static void Trans_C(Env env) throws Exception {
    Integer z = env.<Integer>recv("B").get();
  }
}
