// Code generated by tempo, DO NOT EDIT.
package send_trans

import runtime "github.com/tempo-lang/tempo/runtime"

// Projection of choreography `Trans`
func Trans_A(env *runtime.Env) {
	var x int = 10
	_ = x
	var y int = runtime.GetAsync(runtime.Send(env, x, "B"))
	_ = y
	var z int = y
	_ = z
}
func Trans_B(env *runtime.Env) {
	var y int = runtime.GetAsync(runtime.Recv[int](env, "A"))
	_ = y
	var z int = runtime.GetAsync(runtime.Send(env, y, "C"))
	_ = z
}
func Trans_C(env *runtime.Env) {
	var z int = runtime.GetAsync(runtime.Recv[int](env, "B"))
	_ = z
}
