// Code generated by tempo, DO NOT EDIT.
package shift_roles

import runtime "tempo/runtime"

// Projection of choreography ShiftRoles
func ShiftRoles_A(env *runtime.Env, count int) {
	if count > 0 {
		env.Send(count, "B")
		_ = count
		ShiftRoles_D(env.Subst("B", "A", "C", "B", "D", "C", "A", "D"), count-1)
	}
}
func ShiftRoles_B(env *runtime.Env, count int) {
	if count > 0 {
		_ = env.Recv("A").Get().(int)
		ShiftRoles_A(env.Subst("B", "A", "C", "B", "D", "C", "A", "D"), count-1)
	}
}
func ShiftRoles_C(env *runtime.Env, count int) {
	if count > 0 {
		_ = count
		ShiftRoles_B(env.Subst("B", "A", "C", "B", "D", "C", "A", "D"), count-1)
	}
}
func ShiftRoles_D(env *runtime.Env, count int) {
	if count > 0 {
		_ = count
		ShiftRoles_C(env.Subst("B", "A", "C", "B", "D", "C", "A", "D"), count-1)
	}
}
