package epp

import (
	"chorego/parser"
	"fmt"

	"github.com/dave/jennifer/jen"
)

func EppFunc(function parser.IFuncContext) *jen.File {
	func_role := function.Role_type_normal()
	func_name := function.Ident().GetText()

	file := jen.NewFile("choreography")

	// 3. Add a package comment, so IDEs detect files as generated
	file.PackageComment("Code generated by chorego, DO NOT EDIT.")

	file.Comment(fmt.Sprintf("Projection of %s", func_name))
	for _, roleNode := range func_role.AllIdent() {
		role := roleNode.ID().GetText()
		file.Func().Id(fmt.Sprintf("%s_%s", func_name, role)).Params().Block()
	}

	return file
}
