// Code generated by tempo, DO NOT EDIT.

import { Env } from '../../typescript/runtime.ts';

// Projection of interface `Math`
export interface Math_A {
  Exp(env: Env, base: number, exp: number): Promise<number>;
}

// Projection of struct `Secret`
export type Secret_A = {
  A: number;
}
export type Secret_B = {
  B: number;
}

// Projection of choreography `DiffieHellman`
export async function DiffieHellman_A(env: Env, mathA: Math_A): Promise<Secret_A> {
  let p: number = 23;
  let g: number = 5;
  let a: number = 4;
  env.send(Math.floor(await mathA.Exp(env.subst("A", "A"), g, a) % p), "B");
  let B: Promise<number> = env.recv<number>("B");
  let sA: number = Math.floor(await mathA.Exp(env.subst("A", "A"), await B, a) % p);
  return { A: sA };
}
export async function DiffieHellman_B(env: Env, mathB: Math_A): Promise<Secret_B> {
  let p: number = 23;
  let g: number = 5;
  let b: number = 3;
  let A: Promise<number> = env.recv<number>("A");
  env.send(Math.floor(await mathB.Exp(env.subst("B", "A"), g, b) % p), "A");
  let sB: number = Math.floor(await mathB.Exp(env.subst("B", "A"), await A, b) % p);
  return { B: sB };
}

