// Code generated by tempo, DO NOT EDIT.
package send_simple;

import tempo.runtime.Env;

public final class Choreography {
  private Choreography() {}
  
  // Projection of choreography `SimpleSend`
  public static void SimpleSend_A(Env env) throws Exception {
    Integer x = 10;
    env.send(x, "B").get();
  }
  public static void SimpleSend_B(Env env) throws Exception {
    Integer y = env.<Integer>recv("A").get();
  }
}
