// Code generated by tempo, DO NOT EDIT.

import { Env } from '../../typescript/runtime.ts';

// Projection of choreography `SimpleSend`
export async function SimpleSend_A(env: Env) {
  let x: number = 10;
  env.send(x, "B");
}
export async function SimpleSend_B(env: Env) {
  let y: number = await env.recv<number>("A");
}

