// Code generated by tempo, DO NOT EDIT.

import { Env } from '../../../typescript/runtime.ts';

// Projection of choreography `foo`
export async function foo_A(env: Env) {
  let closure: (env: Env, arg0: number) => Promise<void> = async (env: Env, input: number) => {
    await env.send(input, "B");
  };
  await closure(env, 10);
}
export async function foo_B(env: Env) {
  let closure: (env: Env) => Promise<number> = async (env: Env): Promise<number> => {
    return await env.recv<number>("A");
  };
  let result: number = await closure(env);
}

