// Code generated by tempo, DO NOT EDIT.
package choreography

import runtime "github.com/tempo-lang/tempo/runtime"

// Projection of choreography `double`
func double_A(env *runtime.Env, val int) int {
	return val * 2
}

// Projection of choreography `main`
func main_A(env *runtime.Env) {
	var a func(int) int = func(val int) int {
		return double_A(env.Subst("A", "A"), val)
	}
	_ = a
	var b func(int) int = runtime.Copy(a)
	_ = b
}
func main_B(env *runtime.Env) {
	var a func(int) int = func(val int) int {
		return double_A(env.Subst("B", "A"), val)
	}
	_ = a
	var b func(int) int = runtime.Copy(a)
	_ = b
	var x func(int) int = runtime.Copy(a)
	_ = x
	var y func(int) int = func(val int) int {
		return double_A(env.Subst("B", "A"), val)
	}
	_ = y
}
