// Code generated by tempo, DO NOT EDIT.
package choreography

import runtime "github.com/tempo-lang/tempo/runtime"

// Projection of choreography `foo`
func foo_A(env *runtime.Env) {
	var closure func(int) = func(input int) {
		_ = runtime.GetAsync(runtime.Send(env, input, "B"))
	}
	_ = closure
	closure(10)
}
func foo_B(env *runtime.Env) {
	var closure func() int = func() int {
		return runtime.GetAsync(runtime.Recv[int](env, "A"))
	}
	_ = closure
	var result int = closure()
	_ = result
}
