// Code generated by tempo, DO NOT EDIT.

import { Env } from '../../../typescript/runtime.ts';

// Projection of choreography call
export async function call_X(env: Env, val: number) {
}

// Projection of choreography call2
export async function call2_Y(env: Env, param: number) {
}

// Projection of choreography foo
export async function foo_A(env: Env) {
  let x: (env: Env, arg0: number) => Promise<void> = async (env: Env, val: number) => {
    await call_X(env.subst("A", "X"), val);
  };
  x = async (env: Env, param: number) => {
    await call2_Y(env.subst("A", "Y"), param);
  };
  await x(env, 10);
}
export async function foo_B(env: Env) {
}

