// Code generated by tempo, DO NOT EDIT.
package choreography

import runtime "github.com/tempo-lang/tempo/runtime"

// Projection of choreography constants
func constants_A(env *runtime.Env) {
	var intValue int = 123
	_ = intValue
	var floatValue float64 = 123.0
	_ = floatValue
	var booleanValue bool = true
	_ = booleanValue
	var stringValue string = "Hello"
	_ = stringValue
}
