// Code generated by tempo, DO NOT EDIT.
package choreography

import runtime "github.com/tempo-lang/tempo/runtime"

// Projection of choreography constants
func constants_A(env *runtime.Env) {
	var intValue int = runtime.Copy(123)
	_ = intValue
	var floatValue float64 = runtime.Copy(123.0)
	_ = floatValue
	var booleanValue bool = runtime.Copy(true)
	_ = booleanValue
	var stringValue string = runtime.Copy("Hello")
	_ = stringValue
}
