// Code generated by tempo, DO NOT EDIT.
package choreography

import runtime "tempo/runtime"

// Projection of choreography constants
func constants_A(env *runtime.Env) {
	var numberValue int = 123
	_ = numberValue
	var booleanValue bool = true
	_ = booleanValue
}
