// Code generated by tempo, DO NOT EDIT.

import { Env } from '../../../typescript/runtime.ts';

// Projection of choreography constants
export async function constants_A(env: Env) {
  let intValue: number = env.copy(123);
  let floatValue: number = env.copy(123.000000);
  let booleanValue: boolean = env.copy(true);
  let stringValue: string = env.copy("Hello");
}

