// Code generated by tempo, DO NOT EDIT.

import { Env } from '../../../typescript/runtime.ts';

// Projection of choreography `send`
export async function send_X(env: Env, value: number) {
  env.send(value, "Y");
}
export async function send_Y(env: Env): Promise<number> {
  return await env.recv<number>("X");
}

// Projection of choreography `foo`
export async function foo_A(env: Env) {
  let x: number = 10;
  await send_X(env.subst("A", "X", "B", "Y"), x);
}
export async function foo_B(env: Env) {
  let Y: number = await send_Y(env.subst("A", "X", "B", "Y"));
}

