// Code generated by tempo, DO NOT EDIT.
package choreography

import runtime "tempo/runtime"

// Projection of choreography foo
func foo_A(env *runtime.Env) {
	var x *runtime.Async = runtime.FixedAsync(10)
	_ = x
}
