// Code generated by tempo, DO NOT EDIT.

import { Env } from '../../../typescript/runtime.ts';

// Projection of choreography foo
export async function foo_A(env: Env) {
  let x: string = env.copy("AB");
}
export async function foo_B(env: Env) {
  let x: string = env.copy("AB");
  let y: string = env.copy("BC");
  let z: string[] = env.copy([x, y]);
}
export async function foo_C(env: Env) {
  let y: string = env.copy("BC");
}

