// Code generated by tempo, DO NOT EDIT.

import { Env } from '../../../typescript/runtime.ts';

// Projection of choreography `foo`
export async function foo_A(env: Env) {
  let result: number = await env.recv<number>("B");
}
export async function foo_B(env: Env) {
  await env.send(await env.recv<number>("A"), "A");
}

