// Code generated by tempo, DO NOT EDIT.
package choreography

import runtime "github.com/tempo-lang/tempo/runtime"

// Projection of choreography `foo`
func foo_A(env *runtime.Env) {
	var x []int = []int{1, 2, 3}
	_ = x
	var y []int = runtime.Copy(x)
	_ = y
}
func foo_B(env *runtime.Env) {
	var x []int = []int{1, 2, 3}
	_ = x
}
