// Code generated by tempo, DO NOT EDIT.

import { Env } from '../../../typescript/runtime.ts';

// Projection of choreography `foo`
export async function foo_A(env: Env) {
  let x: number = Math.floor(Math.floor(2 + 3 - 4 * 5 / 6) % 7);
  let y: string = "hello" + " world";
  let z: number = 2.0 + 3.0 - 4.0 * 5.0 / 6.0;
  let w: boolean = true && false || true;
}
