// Code generated by tempo, DO NOT EDIT.
package choreography

import runtime "github.com/tempo-lang/tempo/runtime"

// Projection of choreography foo
func foo_A(env *runtime.Env) {
	var x []int = runtime.Copy([]int{1, 2, 3})
	_ = x
}
func foo_B(env *runtime.Env) {
	var x []int = runtime.Copy([]int{1, 2, 3})
	_ = x
	var i int = runtime.Copy(1)
	_ = i
	var y int = runtime.Copy(x[i])
	_ = y
}
func foo_C(env *runtime.Env) {
	var i int = runtime.Copy(1)
	_ = i
}
