// Code generated by tempo, DO NOT EDIT.

import { Env } from '../../../typescript/runtime.ts';

// Projection of choreography foo
export async function foo_A(env: Env) {
  env.send(10, "B");
}
export async function foo_B(env: Env) {
  let value: Promise<number> = env.copy(env.recv("A"));
  let another: number = env.copy(await value);
}

