// Code generated by tempo, DO NOT EDIT.

import { Env } from '../../../typescript/runtime.ts';

// Projection of choreography `foo`
export async function foo_A(env: Env) {
  let x: Promise<number> = Promise.resolve(10);
}

