// Code generated by tempo, DO NOT EDIT.
package choreography

import runtime "github.com/tempo-lang/tempo/runtime"

// Projection of choreography foo
func foo_A(env *runtime.Env) {
	runtime.Send(env, 10, "B")
}
func foo_B(env *runtime.Env) {
	var value *runtime.Async[int] = runtime.Copy(runtime.Recv[int](env, "A"))
	_ = value
	var another int = runtime.Copy(runtime.GetAsync(value))
	_ = another
}
