// Code generated by tempo, DO NOT EDIT.
package choreography

import runtime "tempo/runtime"

// Projection of choreography foo
func foo_A(env *runtime.Env) {
	env.Send(10, "B")
	var result int = env.Recv("B").Get().(int)
	_ = result
}
func foo_B(env *runtime.Env) {
	var tmp0 *runtime.Async = runtime.FixedAsync(env.Recv("A").Get().(int))
	_ = tmp0
	env.Send(tmp0.Get().(int), "A")
}
