// Code generated by tempo, DO NOT EDIT.
package choreography

import runtime "github.com/tempo-lang/tempo/runtime"

// Projection of choreography foo
func foo_A(env *runtime.Env) {
	var x *runtime.Async[int] = runtime.Copy(runtime.FixedAsync(10))
	_ = x
	var y int = runtime.Copy(runtime.GetAsync(x))
	_ = y
}
