// Code generated by tempo, DO NOT EDIT.
package choreography

import runtime "github.com/tempo-lang/tempo/runtime"

// Projection of choreography `foo`
func foo_A(env *runtime.Env) {
	var result int = runtime.GetAsync(runtime.Recv[int](env, "B"))
	_ = result
}
func foo_B(env *runtime.Env) {
	_ = runtime.GetAsync(runtime.Send(env, runtime.GetAsync(runtime.Recv[int](env, "A")), "A"))
}
