// Code generated by tempo, DO NOT EDIT.
package choreography

import runtime "github.com/tempo-lang/tempo/runtime"

// Projection of struct `Pair`
type Pair_A struct {
	x int `json:"x"`
}
type Pair_B struct {
	y int `json:"y"`
}

// Projection of choreography `main`
func main_A(env *runtime.Env) {
	var pairs []Pair_A = []Pair_A{Pair_A{x: 10}}
	_ = pairs
	var i int = 0
	_ = i
	if true {
		pairs[i].x = 30
	}
}
func main_B(env *runtime.Env) {
	var pairs []Pair_B = []Pair_B{Pair_B{y: 20}}
	_ = pairs
	var i int = 0
	_ = i
}
