// Code generated by tempo, DO NOT EDIT.
package choreography

import runtime "tempo/runtime"

// Projection of choreography foo
func foo_A(env *runtime.Env) {
	var x int = 10
	_ = x
	env.Send(x, "B")
	var y int = x
	_ = y
	var z int = y
	_ = z
}
func foo_B(env *runtime.Env) {
	var y int = env.Recv("A").Get().(int)
	_ = y
	env.Send(y, "C")
	var z int = y
	_ = z
}
func foo_C(env *runtime.Env) {
	var z int = env.Recv("B").Get().(int)
	_ = z
}
