// Code generated by tempo, DO NOT EDIT.

import { Env } from '../../../typescript/runtime.ts';

// Projection of choreography binOps
export async function binOps_A(env: Env) {
  let a: number = 1 + 2 - 3 * 4 / 5 % 6;
  let b: boolean = true === true;
  let c: boolean = false !== false;
  let d: boolean = 10 < 20;
  let e: boolean = 10 <= 20;
  let f: boolean = 10 > 20;
  let g: boolean = 10 >= 20;
}

