// Code generated by tempo, DO NOT EDIT.
package choreography

import runtime "github.com/tempo-lang/tempo/runtime"

// Projection of choreography assign
func assign_A(env *runtime.Env) {
	var x int = runtime.Copy(10)
	_ = x
	x = runtime.Copy(20)
}
