// Code generated by tempo, DO NOT EDIT.

import { Env } from '../../../typescript/runtime.ts';

// Projection of choreography foo
export async function foo_A(env: Env) {
  let x: number = env.copy(10);
  env.send(x, "B");
  let y: number = env.copy(x);
  let z: number = env.copy(y);
}
export async function foo_B(env: Env) {
  let y: number = env.copy(await env.recv("A"));
  env.send(y, "C");
  let z: number = env.copy(y);
}
export async function foo_C(env: Env) {
  let z: number = env.copy(await env.recv("B"));
}

