// Code generated by tempo, DO NOT EDIT.
package choreography

import runtime "tempo/runtime"

// Projection of choreography binOps
func binOps_A(env *runtime.Env) {
	var a int = 1 + 2 - 3*4/5
	_ = a
	var b bool = true == false
	_ = b
	var c bool = true != false
	_ = c
	var d bool = 10 < 20
	_ = d
	var e bool = 10 <= 20
	_ = e
	var f bool = 10 > 20
	_ = f
	var g bool = 10 >= 20
	_ = g
}
