// Code generated by tempo, DO NOT EDIT.

import { Env } from '../../../typescript/runtime.ts';

// Projection of choreography `foo`
export async function foo_A(env: Env) {
  let x: number = 10;
  let y: number = await env.send(x, "B", "C");
}
export async function foo_B(env: Env) {
  let y: number = await env.recv<number>("A");
}
export async function foo_C(env: Env) {
  let y: number = await env.recv<number>("A");
}

