// Code generated by tempo, DO NOT EDIT.
package choreography

import runtime "github.com/tempo-lang/tempo/runtime"

// Projection of choreography foo
func foo_A(env *runtime.Env) {
	var x []int = runtime.Copy(append([]int{1, 2, 3}, []int{4, 5, 6}...))
	_ = x
}
func foo_B(env *runtime.Env) {
	var x []int = runtime.Copy(append([]int{1, 2, 3}, []int{4, 5, 6}...))
	_ = x
}
