// Code generated by tempo, DO NOT EDIT.

import { Env } from '../../../typescript/runtime.ts';

// Projection of choreography foo
export async function foo_A(env: Env) {
  let x: string = "AB";
}
export async function foo_B(env: Env) {
  let x: string = "AB";
  let y: string = "BC";
  let z: string[] = [x, y];
}
export async function foo_C(env: Env) {
  let y: string = "BC";
}

