// Code generated by tempo, DO NOT EDIT.

import { Env } from '../../../typescript/runtime.ts';

// Projection of choreography foo
export async function foo_A(env: Env) {
  let x: number[] = [1, 2, 3];
  let y: number[] = env.copy(x);
}
export async function foo_B(env: Env) {
  let x: number[] = [1, 2, 3];
}

