// Code generated by tempo, DO NOT EDIT.

import { Env } from '../../../typescript/runtime.ts';

// Projection of struct `Pair`
export interface Pair_A_attrs {
  x: number;
}
export class Pair_A implements Pair_A_attrs {
  x: number;
  
  constructor({ x }: Pair_A_attrs) {
    this.x = x;
  }
}

export interface Pair_B_attrs {
  y: number;
}
export class Pair_B implements Pair_B_attrs {
  y: number;
  
  constructor({ y }: Pair_B_attrs) {
    this.y = y;
  }
}


// Projection of choreography `main`
export async function main_A(env: Env) {
  let pairs: Pair_A[] = [new Pair_A({ x: 10 })];
  let i: number = 0;
  if (true) {
    pairs[i].x = 30;
  }
}
export async function main_B(env: Env) {
  let pairs: Pair_B[] = [new Pair_B({ y: 20 })];
  let i: number = 0;
}

