// Code generated by tempo, DO NOT EDIT.

import { Env } from '../../../typescript/runtime.ts';

// Projection of choreography foo
export async function foo_A(env: Env) {
  let x: number[] = [1, 2, 3].concat([4, 5, 6]);
}
export async function foo_B(env: Env) {
  let x: number[] = [1, 2, 3].concat([4, 5, 6]);
}

