// Code generated by tempo, DO NOT EDIT.

import { Env } from '../../../typescript/runtime.ts';

// Projection of choreography foo
export async function foo_A(env: Env) {
  let x: number = 10;
  env.send(x, "B", "C");
  let y: number = env.copy(x);
}
export async function foo_B(env: Env) {
  let y: number = await env.recv("A");
}
export async function foo_C(env: Env) {
  let y: number = await env.recv("A");
}

