// Code generated by tempo, DO NOT EDIT.
package choreography

import runtime "tempo/runtime"

// Projection of choreography foo
func foo_A(env *runtime.Env) {
	var x int = 10
	_ = x
	runtime.Send(env, x, "B", "C")
	var y int = x
	_ = y
}
func foo_B(env *runtime.Env) {
	var y int = runtime.GetAsync(runtime.Recv[int](env, "A"))
	_ = y
}
func foo_C(env *runtime.Env) {
	var y int = runtime.GetAsync(runtime.Recv[int](env, "A"))
	_ = y
}
