// Code generated by tempo, DO NOT EDIT.
package choreography

import runtime "github.com/tempo-lang/tempo/runtime"

// Projection of choreography foo
func foo_A(env *runtime.Env) {
	var x string = "AB"
	_ = x
}
func foo_B(env *runtime.Env) {
	var x string = "AB"
	_ = x
	var y string = "BC"
	_ = y
	var z []string = runtime.Copy([]string{x, y})
	_ = z
}
func foo_C(env *runtime.Env) {
	var y string = "BC"
	_ = y
}
