// Code generated by tempo, DO NOT EDIT.

import { Env } from '../../../typescript/runtime.ts';

// Projection of choreography assign
export async function assign_A(env: Env) {
  let x: number = env.copy(10);
  x = env.copy(20);
}

