// Code generated by tempo, DO NOT EDIT.
package choreography

import runtime "github.com/tempo-lang/tempo/runtime"

// Projection of choreography foo
func foo_A(env *runtime.Env) {
	var x int = 10
	_ = x
	runtime.Send(env, x, "B")
	var y int = x
	_ = y
	var z int = y
	_ = z
}
func foo_B(env *runtime.Env) {
	var y int = runtime.GetAsync(runtime.Recv[int](env, "A"))
	_ = y
	runtime.Send(env, y, "C")
	var z int = y
	_ = z
}
func foo_C(env *runtime.Env) {
	var z int = runtime.GetAsync(runtime.Recv[int](env, "B"))
	_ = z
}
