// Code generated by tempo, DO NOT EDIT.
package choreography

import runtime "tempo/runtime"

// Projection of choreography foo
func foo_A(env *runtime.Env) {
	runtime.Send(env, 10, "A")
	var x int = runtime.GetAsync(runtime.Recv[int](env, "A"))
	_ = x
}
