// Code generated by tempo, DO NOT EDIT.

import { Env } from '../../../typescript/runtime.ts';

// Projection of choreography `floats`
export async function floats_A(env: Env) {
  let a: number = 10.5;
  let b: number = 10.00000009;
  let c: number = 1.0;
}

