// Code generated by tempo, DO NOT EDIT.
package choreography

import runtime "github.com/tempo-lang/tempo/runtime"

// Projection of choreography `floats`
func floats_A(env *runtime.Env) {
	var a float64 = 10.5
	_ = a
	var b float64 = 10.00000009
	_ = b
	var c float64 = 1.0
	_ = c
}
