// Code generated by tempo, DO NOT EDIT.
package choreography

import runtime "github.com/tempo-lang/tempo/runtime"

// Projection of choreography `double`
func double_A(env *runtime.Env, val int) int {
	return val * 2
}

// Projection of choreography `main`
func main_A(env *runtime.Env) {
	var x int = double_A(env, 10)
	_ = x
}
func main_B(env *runtime.Env) {
	var x int = double_A(env.Subst("B", "A"), 10)
	_ = x
}
