// Code generated by tempo, DO NOT EDIT.

import { Env } from '../../../typescript/runtime.ts';

// Projection of choreography foo
export async function foo_X(env: Env) {
}
export async function foo_Y(env: Env) {
}
export async function foo_Z(env: Env) {
}

