// Code generated by tempo, DO NOT EDIT.

import { Env } from '../../../typescript/runtime.ts';

// Projection of choreography `foo`
export async function foo_B(env: Env, snd: number) {
}
export async function foo_A(env: Env, snd: number) {
}

