// Code generated by tempo, DO NOT EDIT.

import { Env } from '../../../typescript/runtime.ts';

// Projection of choreography foo
export async function foo_A(env: Env, fst: number, snd: string) {
}
export async function foo_B(env: Env, snd: string) {
}
export async function foo_C(env: Env) {
}

