// Code generated by tempo, DO NOT EDIT.
package choreography

import runtime "github.com/tempo-lang/tempo/runtime"

// Projection of choreography foo
func foo_A(env *runtime.Env, value int, fn func(*runtime.Env, int)) {
	fn(env.Subst("A", "A", "B", "B"), value)
}
func foo_B(env *runtime.Env, fn func(*runtime.Env) int) int {
	return fn(env.Subst("A", "A", "B", "B"))
}
