// Code generated by tempo, DO NOT EDIT.
package choreography

import runtime "github.com/tempo-lang/tempo/runtime"

// Projection of choreography `foo`
func foo_B(env *runtime.Env, snd int) {}
func foo_A(env *runtime.Env, snd int) {}
