// Code generated by tempo, DO NOT EDIT.
package choreography

import runtime "github.com/tempo-lang/tempo/runtime"

// Projection of struct `Pair`
type Pair_A struct {
	x int `json:"x"`
}
type Pair_B struct {
	y int `json:"y"`
}

// Projection of choreography `foo`
func foo_A(env *runtime.Env) {
	var pair []Pair_A = []Pair_A{Pair_A{x: 10}}
	_ = pair
	var i int = 0
	_ = i
	var x int = pair[i].x
	_ = x
}
func foo_B(env *runtime.Env) {
	var pair []Pair_B = []Pair_B{Pair_B{y: 20}}
	_ = pair
	if true {
		var y int = pair[0].y
		_ = y
	}
}
func foo_C(env *runtime.Env) {}
