// Code generated by tempo, DO NOT EDIT.
package choreography

import runtime "github.com/tempo-lang/tempo/runtime"

// Projection of struct `Pair`
type Pair_A struct {
	x int `json:"x"`
}
type Pair_B struct {
	y int `json:"y"`
}

// Projection of choreography `main`
func main_A(env *runtime.Env) {
	var pair Pair_A = Pair_A{x: 10}
	_ = pair
}
func main_B(env *runtime.Env) {}
