// Code generated by tempo, DO NOT EDIT.
package choreography

import runtime "github.com/tempo-lang/tempo/runtime"

// Projection of struct `Pair`
type Pair_A struct {
	x int `json:"x"`
}
type Pair_B struct {
	y int `json:"y"`
}

// Projection of choreography `combine`
func combine_A(env *runtime.Env, pairA Pair_A) Pair_A {
	return Pair_A{x: pairA.x}
}
func combine_B(env *runtime.Env, pairB Pair_B) Pair_B {
	return Pair_B{y: pairB.y}
}

// Projection of choreography `main`
func main_A(env *runtime.Env) {
	var pairA Pair_A = Pair_A{x: 10}
	_ = pairA
	var result Pair_A = combine_A(env, runtime.Copy(pairA))
	_ = result
}
func main_B(env *runtime.Env) {
	var pairB Pair_B = Pair_B{y: 20}
	_ = pairB
	var result Pair_B = combine_B(env, runtime.Copy(pairB))
	_ = result
}
