// Code generated by tempo, DO NOT EDIT.

import { Env } from '../../../typescript/runtime.ts';

// Projection of struct `Pair`
export interface Pair_A_attrs {
  x: number;
}
export class Pair_A implements Pair_A_attrs {
  x: number;
  
  constructor({ x }: Pair_A_attrs) {
    this.x = x;
  }
}

export interface Pair_B_attrs {
  y: number;
}
export class Pair_B implements Pair_B_attrs {
  y: number;
  
  constructor({ y }: Pair_B_attrs) {
    this.y = y;
  }
}


// Projection of choreography `combine`
export async function combine_A(env: Env, pairA: Pair_A): Promise<Pair_A> {
  return new Pair_A({ x: pairA.x });
}
export async function combine_B(env: Env, pairB: Pair_B): Promise<Pair_B> {
  return new Pair_B({ y: pairB.y });
}

// Projection of choreography `main`
export async function main_A(env: Env) {
  let pairA: Pair_A = new Pair_A({ x: 10 });
  let result: Pair_A = await combine_A(env, env.copy(pairA));
}
export async function main_B(env: Env) {
  let pairB: Pair_B = new Pair_B({ y: 20 });
  let result: Pair_B = await combine_B(env, env.copy(pairB));
}

