// Code generated by tempo, DO NOT EDIT.
package choreography

import runtime "github.com/tempo-lang/tempo/runtime"

// Projection of interface Action
type Action_A interface {
	foo(env *runtime.Env)
	callA(env *runtime.Env)
}
type Action_B interface {
	foo(env *runtime.Env)
	callB(env *runtime.Env)
}

// Projection of choreography start
func start_X(env *runtime.Env, action Action_A) {
	action.foo(env.Subst("X", "A", "Y", "B"))
}
func start_Y(env *runtime.Env, action Action_B) {
	action.foo(env.Subst("X", "A", "Y", "B"))
}
