// Code generated by tempo, DO NOT EDIT.

import { Env } from '../../../typescript/runtime.ts';

// Projection of interface `Action`
export interface Action_A {
  foo(env: Env): Promise<void>;
  callA(env: Env): Promise<void>;
}
export interface Action_B {
  foo(env: Env): Promise<void>;
  callB(env: Env): Promise<void>;
}

// Projection of choreography `start`
export async function start_X(env: Env, action: Action_A) {
  await action.foo(env.subst("X", "A", "Y", "B"));
}
export async function start_Y(env: Env, action: Action_B) {
  await action.foo(env.subst("X", "A", "Y", "B"));
}

