// Code generated by tempo, DO NOT EDIT.
package choreography

import runtime "github.com/tempo-lang/tempo/runtime"

// Projection of interface Sum
type Sum_X interface {
	sum(env *runtime.Env, a int, b int) int
}

// Projection of choreography foo
func foo_A(env *runtime.Env, x Sum_X) {
	var value int = runtime.Copy(x.sum(env.Subst("A", "X"), runtime.Copy(10), runtime.Copy(20)))
	_ = value
}
