// Code generated by tempo, DO NOT EDIT.

import { Env } from '../../../typescript/runtime.ts';

// Projection of struct `Pair`
export interface Pair_A_attrs {
  x: number;
}
export class Pair_A implements Pair_A_attrs {
  x: number;
  
  constructor({ x }: Pair_A_attrs) {
    this.x = x;
  }
}

export interface Pair_B_attrs {
  y: number;
}
export class Pair_B implements Pair_B_attrs {
  y: number;
  
  constructor({ y }: Pair_B_attrs) {
    this.y = y;
  }
}


// Projection of choreography `main`
export async function main_A(env: Env) {
  let pair: Pair_A = new Pair_A({ x: 10 });
  if (true) {
    let inner: Pair_A = env.copy(pair);
  }
}
export async function main_B(env: Env) {
  let x: number = 10;
  if (true) {
    let y: number = x;
  }
}
export async function main_C(env: Env) {
  let pair: Pair_B = new Pair_B({ y: 20 });
  let x: number = 10;
}

