// Code generated by tempo, DO NOT EDIT.
package choreography

import runtime "tempo/runtime"

// Projection of choreography shareSubset
func shareSubset_A(env *runtime.Env) {
	var x int = 10
	_ = x
	var y int = x
	_ = y
	var z int = y
	_ = z
}
func shareSubset_B(env *runtime.Env) {
	var x int = 10
	_ = x
	var y int = x
	_ = y
}
func shareSubset_C(env *runtime.Env) {
	var x int = 10
	_ = x
}
