// Code generated by tempo, DO NOT EDIT.
package choreography

import runtime "github.com/tempo-lang/tempo/runtime"

// Projection of struct `Foo`
type Foo_A struct {
	x int `json:"x"`
	y int `json:"y"`
}

// Projection of choreography `main`
func main_A(env *runtime.Env) {
	var foo Foo_A = Foo_A{
		x: 10,
		y: 20,
	}
	_ = foo
	var fooShared Foo_A = runtime.GetAsync(runtime.Send(env, foo, "B"))
	_ = fooShared
	var x int = fooShared.x
	_ = x
}
func main_B(env *runtime.Env) {
	var fooShared Foo_A = runtime.GetAsync(runtime.Recv[Foo_A](env, "A"))
	_ = fooShared
	var x int = fooShared.x
	_ = x
}
