// Code generated by tempo, DO NOT EDIT.
package choreography

import runtime "github.com/tempo-lang/tempo/runtime"

// Projection of choreography shareSubset
func shareSubset_A(env *runtime.Env) {
	var x int = runtime.Copy(10)
	_ = x
	var y int = runtime.Copy(x)
	_ = y
	var z int = runtime.Copy(y)
	_ = z
}
func shareSubset_B(env *runtime.Env) {
	var x int = runtime.Copy(10)
	_ = x
	var y int = runtime.Copy(x)
	_ = y
}
func shareSubset_C(env *runtime.Env) {
	var x int = runtime.Copy(10)
	_ = x
}
