// Code generated by tempo, DO NOT EDIT.
package choreography

import runtime "tempo/runtime"

// Projection of choreography shared
func shared_A(env *runtime.Env) {
	var x int = 10
	_ = x
}
func shared_B(env *runtime.Env) {
	var x int = 10
	_ = x
}
