// Code generated by tempo, DO NOT EDIT.

import { Env } from '../../../typescript/runtime.ts';

// Projection of choreography foo
export async function foo_A(env: Env) {
  let x: number = 10;
}
export async function foo_B(env: Env) {
  let x: number = 10;
  let y: number = 20;
  let z: number = x + y;
}
export async function foo_C(env: Env) {
  let y: number = 20;
}

