// Code generated by tempo, DO NOT EDIT.
package choreography

import runtime "github.com/tempo-lang/tempo/runtime"

// Projection of choreography foo
func foo_A(env *runtime.Env) {
	var x int = 10
	_ = x
}
func foo_B(env *runtime.Env) {
	var x int = 10
	_ = x
	var y int = 20
	_ = y
	var z int = x + y
	_ = z
}
func foo_C(env *runtime.Env) {
	var y int = 20
	_ = y
}
