// Code generated by tempo, DO NOT EDIT.
package choreography

import runtime "github.com/tempo-lang/tempo/runtime"

// Projection of choreography shared
func shared_A(env *runtime.Env) {
	var x int = runtime.Copy(10)
	_ = x
}
func shared_B(env *runtime.Env) {
	var x int = runtime.Copy(10)
	_ = x
}
