// Code generated by tempo, DO NOT EDIT.
package choreography

import runtime "github.com/tempo-lang/tempo/runtime"

// Projection of choreography countdown
func countdown_A(env *runtime.Env) {
	var x int = 10
	_ = x
	for x > 0 {
		x = runtime.Copy(x - 1)
	}
}
