// Code generated by tempo, DO NOT EDIT.

import { Env } from '../../../typescript/runtime.ts';

// Projection of choreography countdown
export async function countdown_A(env: Env) {
  let x: number = env.copy(10);
  while (x > 0) {
    x = env.copy(x - 1);
  }
}

