// Code generated by tempo, DO NOT EDIT.
package choreography

import runtime "github.com/tempo-lang/tempo/runtime"

// Projection of choreography call
func call_X(env *runtime.Env) {}

// Projection of choreography foo
func foo_A(env *runtime.Env) {
	var x func(*runtime.Env) = call_X
	_ = x
	x(env.Subst("A", "X"))
}
func foo_B(env *runtime.Env) {
	var y func(*runtime.Env) = call_X
	_ = y
	y(env.Subst("B", "X"))
}
