// Code generated by tempo, DO NOT EDIT.

import { Env } from '../../../typescript/runtime.ts';

// Projection of struct Pair
export type Pair_A = {
  x: number;
}
export type Pair_B = {
  y: number;
}
