// Code generated by tempo, DO NOT EDIT.

import { Env } from '../../../typescript/runtime.ts';

// Projection of struct `Foo`
export type Foo_A = {
}
export type Foo_B = {
}

// Implementation of struct `Foo`
function Foo_A_methods(self: Foo_A) {
  return {
    async onlyAtA(env: Env) {
    },
  };
}
function Foo_B_methods(self: Foo_B) {
  return {
  };
}

