// Code generated by tempo, DO NOT EDIT.
package choreography

import runtime "github.com/tempo-lang/tempo/runtime"

// Projection of struct `Pair`
type Pair_A struct {
	x int `json:"x"`
}
type Pair_B struct {
	y int `json:"y"`
}

// Implementation of struct `Pair`
func (self Pair_A) swap(env *runtime.Env) Pair_B {
	return Pair_B{y: self.x}
}
func (self Pair_B) swap(env *runtime.Env) Pair_A {
	return Pair_A{x: self.y}
}
