// Code generated by tempo, DO NOT EDIT.
package choreography

import runtime "tempo/runtime"

// Projection of struct Foo
type Foo_A struct {
	first  Bar_X `json:"first"`
	second Bar_Y `json:"second"`
}
type Foo_B struct {
	first  Bar_Y `json:"first"`
	second Bar_X `json:"second"`
}

// Projection of struct Bar
type Bar_X struct {
	num int `json:"num"`
}
type Bar_Y struct {
	logic bool `json:"logic"`
}

// Projection of choreography foo
func foo_P(env *runtime.Env) {
	var x int = 10
	_ = x
	var nested Foo_A = Foo_A{
		first:  Bar_X{num: x},
		second: Bar_Y{logic: false},
	}
	_ = nested
}
func foo_Q(env *runtime.Env) {
	var y int = 20
	_ = y
	var nested Foo_B = Foo_B{
		first:  Bar_Y{logic: true},
		second: Bar_X{num: y},
	}
	_ = nested
}
