// Code generated by tempo, DO NOT EDIT.

import { Env } from '../../../typescript/runtime.ts';

// Projection of struct Foo
export type Foo_A = {
  first: Bar_X;
  second: Bar_Y;
}
export type Foo_B = {
  first: Bar_Y;
  second: Bar_X;
}

// Projection of struct Bar
export type Bar_X = {
  num: number;
}
export type Bar_Y = {
  logic: boolean;
}

// Projection of choreography foo
export async function foo_P(env: Env) {
  let x: number = 10;
  let nested: Foo_A = { first: { num: x }, second: { logic: false } };
}
export async function foo_Q(env: Env) {
  let y: number = 20;
  let nested: Foo_B = { first: { logic: true }, second: { num: y } };
}

