// Code generated by tempo, DO NOT EDIT.
package choreography

import runtime "tempo/runtime"

// Projection of struct Pair
type Pair_A struct {
	num int `json:"num"`
}
type Pair_B struct {
	logic bool `json:"logic"`
}

// Projection of choreography foo
func foo_X(env *runtime.Env) {
	var p Pair_A = Pair_A{num: 1}
	_ = p
}
func foo_Y(env *runtime.Env) {
	var p Pair_B = Pair_B{logic: true}
	_ = p
}
