// Code generated by tempo, DO NOT EDIT.
package choreography

import runtime "github.com/tempo-lang/tempo/runtime"

// Projection of struct `Foo`
type Foo_A struct{}
type Foo_B struct{}

// Implementation of struct `Foo`
func (self Foo_A) onlyAtA(env *runtime.Env) {}
