// Code generated by tempo, DO NOT EDIT.
package choreography

import runtime "github.com/tempo-lang/tempo/runtime"

// Projection of interface `Bar`
type Bar interface {
	bar(env *runtime.Env)
}

// Projection of interface `Baz`
type Baz interface {
	baz(env *runtime.Env)
}

// Projection of struct `Foo`
type Foo_A struct{}
type Foo_B struct{}

// Implementation of struct `Foo`
func (self Foo_A) bar(env *runtime.Env) {}
func (self Foo_B) baz(env *runtime.Env) {}
