// Code generated by tempo, DO NOT EDIT.

import { Env } from '../../../typescript/runtime.ts';

// Projection of interface `Bar`
export interface Bar {
  bar(env: Env): Promise<void>;
}

// Projection of interface `Baz`
export interface Baz {
  baz(env: Env): Promise<void>;
}

// Projection of struct `Foo`
export interface Foo_A_attrs {
}
export class Foo_A implements Foo_A_attrs, Bar {
  constructor({  }: Foo_A_attrs) {
  }
  
  async bar(env: Env) {
  }
}

export interface Foo_B_attrs {
}
export class Foo_B implements Foo_B_attrs, Baz {
  constructor({  }: Foo_B_attrs) {
  }
  
  async baz(env: Env) {
  }
}


