// Code generated by tempo, DO NOT EDIT.

import { Env } from '../../../typescript/runtime.ts';

// Projection of struct `Foo`
export interface Foo_A_attrs {
}
export class Foo_A implements Foo_A_attrs {
  
  constructor({  }: Foo_A_attrs) {
  }
  
  async onlyAtA(env: Env) {
  }
}

export interface Foo_B_attrs {
}
export class Foo_B implements Foo_B_attrs {
  
  constructor({  }: Foo_B_attrs) {
  }
}


