// Code generated by tempo, DO NOT EDIT.

import { Env } from '../../../typescript/runtime.ts';

// Projection of struct Pair
export type Pair_A = {
  num: number;
}
export type Pair_B = {
  logic: boolean;
}

// Projection of choreography foo
export async function foo_X(env: Env) {
  let p: Pair_A = { num: 1 };
  let x: number = p.num;
}
export async function foo_Y(env: Env) {
  let p: Pair_B = { logic: true };
}

