// Code generated by tempo, DO NOT EDIT.

import { Env } from '../../../typescript/runtime.ts';

// Projection of choreography hello
export async function hello_A(env: Env, name: string) {
}
export async function hello_B(env: Env) {
}

// Projection of choreography goodbye
export async function goodbye_A(env: Env) {
}
export async function goodbye_B(env: Env, name: string) {
}

