// Code generated by tempo, DO NOT EDIT.
package choreography

import runtime "github.com/tempo-lang/tempo/runtime"

// Projection of choreography `main`
func main(env *runtime.Env) {
	var integer int = 10
	_ = integer
	var int1 float64 = float64(integer)
	_ = int1
	var int2 int = int(integer)
	_ = int2
	var int3 string = runtime.IntToString(integer)
	_ = int3
	var float float64 = 8.2
	_ = float
	var float1 int = int(float)
	_ = float1
	var float2 float64 = float64(float)
	_ = float2
	var float3 string = runtime.FloatToString(float)
	_ = float3
	var bool bool = true
	_ = bool
	var bool1 string = runtime.BoolToString(bool)
	_ = bool1
}
