// Code generated by tempo, DO NOT EDIT.
package choreography

import runtime "github.com/tempo-lang/tempo/runtime"

// Projection of choreography `foo`
func foo_A(env *runtime.Env) {
	bar(env.Subst("A", ""))
}

// Projection of choreography `bar`
func bar(env *runtime.Env) {
	foo_A(env.Subst("", "A"))
}
