// Code generated by tempo, DO NOT EDIT.

import { Env } from '../../../typescript/runtime.ts';

// Projection of choreography `double`
export async function double(env: Env, val: number): Promise<number> {
  return val * 2;
}

// Projection of choreography `main`
export async function main_A(env: Env) {
  let x: number = 10;
  let y: number = await double(env.subst("A", ""), x);
}

