// Code generated by tempo, DO NOT EDIT.

import { Env } from '../../../typescript/runtime.ts';

// Projection of choreography `foo`
export async function foo_A(env: Env) {
  await bar(env.subst("A", ""));
}

// Projection of choreography `bar`
export async function bar(env: Env) {
  await foo_A(env.subst("", "A"));
}

