// Code generated by tempo, DO NOT EDIT.
package choreography

import runtime "github.com/tempo-lang/tempo/runtime"

// Projection of choreography `double`
func double(env *runtime.Env, val int) int {
	return val * 2
}

// Projection of choreography `main`
func main_A(env *runtime.Env) {
	var x int = 10
	_ = x
	var y int = double(env.Subst("A", ""), x)
	_ = y
}
