// Code generated by tempo, DO NOT EDIT.
package choreography

import runtime "tempo/runtime"

// Projection of choreography foo
func foo_A(env *runtime.Env) {
	var x int = 32
	_ = x
	var y int = x
	_ = y
}
