// Code generated by tempo, DO NOT EDIT.

import { Env } from '../../../typescript/runtime.ts';

// Projection of choreography foo
export async function foo_A(env: Env) {
  let x: number = 32;
  let y: number = env.copy(x);
}

