package process

import "github.com/dave/jennifer/jen"

type Network map[string]*Process

func NewNetwork() *Network {
	return &Network{}
}

// Process returns the process with the given name, creating one if it doesn't exist yet.
func (n Network) Process(name string) *Process {
	proc, exists := n[name]
	if exists {
		return proc
	}

	proc = &Process{
		Name:  name,
		Funcs: []*Func{},
	}
	n[name] = proc

	return proc
}

func (n Network) Codegen(file *jen.File) {
	// 3. Add a package comment, so IDEs detect files as generated
	file.PackageComment("Code generated by chorego, DO NOT EDIT.")

	for _, proc := range n {
		proc.Codegen(file)
	}
}
