// This module is responsible for generating Go source from a projection.
package codegen_go

import (
	"github.com/dave/jennifer/jen"
	"github.com/tempo-lang/tempo/projection"
)

func GenSourceFile(file *jen.File, s *projection.SourceFile) {
	file.PackageComment("Code generated by tempo, DO NOT EDIT.")

	for _, inf := range s.Interfaces {
		GenChoreographyInterface(file, inf)
	}

	for _, st := range s.Structs {
		GenChoreographyStruct(file, st)
	}

	for _, chor := range s.Chors {
		GenChoreography(file, chor)
	}
}
