package tempo.runtime;
// Code generated by tempo, DO NOT EDIT.

public final class Choreography {
  private Choreography() {
  }

  // Projection of choreography `pingPong`
  public static void pingPong_A(Env env, Integer count) throws Exception {
    if (count > 0) {
      env.send(count, "B").get();
      pingPong_B(env.subst("B", "A", "A", "B"), count - 1);
    }
  }

  public static void pingPong_B(Env env, Integer count) throws Exception {
    if (count > 0) {
      env.<Integer>recv("A").get();
      pingPong_A(env.subst("B", "A", "A", "B"), count - 1);
    }
  }

  // Projection of choreography `main`
  public static void main_A(Env env) throws Exception {
    pingPong_A(env, 4);
  }

  public static void main_B(Env env) throws Exception {
    pingPong_B(env, 4);
  }

}
